### ISSUE TITLE
 [71] [Abduction](Part 3 of 8)

### ISSUE THREAD

**Issue by herela** [DragonFire/3.3.5#75]
Donathan иска да се използва Arcane Биндер на ранен Beryl Sorcerer в Beryl Point и да се върнете към Amber Ledge с него , но те сваля от маунта когато пуснеш Arcane Биндер и когато тръгнеш към Amber Ledge ти дава интеръпт. http://www.thottbot.com/quest=11590#screenshots

**Comment by JunkyBulgaria** [comment]
Авто
